package gameInitiation;

import java.util.Date;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import data.ClientPrimaryData;

@SuppressWarnings("serial")
public class InternalFrame extends javax.swing.JDialog {

	ConnectionManager c;
	String Criterion;
	ClientPrimaryData myClientPrimaryData;

	/** Creates new form InternalFrame */
	public InternalFrame(JFrame ListModel, ConnectionManager c,
			ClientPrimaryData myClientPrimaryData) {
		initComponents();
		this.c = c;
		this.myClientPrimaryData = myClientPrimaryData;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		buttonGroup3 = new javax.swing.ButtonGroup();
		buttonGroup4 = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jRadioButton5 = new javax.swing.JRadioButton();
		jRadioButton6 = new javax.swing.JRadioButton();
		jRadioButton7 = new javax.swing.JRadioButton();
		jRadioButton8 = new javax.swing.JRadioButton();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jRadioButton9 = new javax.swing.JRadioButton();
		jRadioButton10 = new javax.swing.JRadioButton();
		jRadioButton11 = new javax.swing.JRadioButton();
		jRadioButton12 = new javax.swing.JRadioButton();
		jRadioButton13 = new javax.swing.JRadioButton();
		jRadioButton14 = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setVisible(true);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel1.setText("Select Winning Criteria");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel2.setText("Select Continents");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel3.setText("Team1 Name:");

		buttonGroup3.add(jRadioButton1);
		jRadioButton1.setText("Time Based (min)");
		jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton1ActionPerformed(evt);
			}
		});

		buttonGroup3.add(jRadioButton2);
		jRadioButton2.setText("Maximum Points");
		jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton2ActionPerformed(evt);
			}
		});

		buttonGroup1.add(jRadioButton3);
		jRadioButton3.setText("1");
		jRadioButton3.setEnabled(false);

		buttonGroup1.add(jRadioButton4);
		jRadioButton4.setText("3");
		jRadioButton4.setEnabled(false);

		buttonGroup1.add(jRadioButton5);
		jRadioButton5.setText("5");
		jRadioButton5.setEnabled(false);

		buttonGroup2.add(jRadioButton6);
		jRadioButton6.setText("100");
		jRadioButton6.setEnabled(false);

		buttonGroup2.add(jRadioButton7);
		jRadioButton7.setText("500");
		jRadioButton7.setEnabled(false);

		buttonGroup2.add(jRadioButton8);
		jRadioButton8.setText("1000");
		jRadioButton8.setEnabled(false);

		jButton1.setText("Submit");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		buttonGroup4.add(jRadioButton9);
		jRadioButton9.setText("Asia");

		buttonGroup4.add(jRadioButton10);
		jRadioButton10.setText("Europe");

		buttonGroup4.add(jRadioButton11);
		jRadioButton11.setText("Australia");

		buttonGroup4.add(jRadioButton12);
		jRadioButton12.setText("Africa");

		buttonGroup4.add(jRadioButton13);
		jRadioButton13.setText("North America");

		buttonGroup4.add(jRadioButton14);
		jRadioButton14.setText("South America");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel4.setText("Team2 Name:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addContainerGap())
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel1)
																												.addContainerGap(
																														400,
																														Short.MAX_VALUE))
																								.addGroup(
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										layout.createSequentialGroup()
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																																.addComponent(
																																		jRadioButton1)
																																.addGroup(
																																		layout.createSequentialGroup()
																																				.addGap(21,
																																						21,
																																						21)
																																				.addGroup(
																																						layout.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																								.addComponent(
																																										jRadioButton5)
																																								.addComponent(
																																										jRadioButton3,
																																										javax.swing.GroupLayout.Alignment.LEADING)
																																								.addComponent(
																																										jRadioButton4,
																																										javax.swing.GroupLayout.Alignment.LEADING))))
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																														253,
																														Short.MAX_VALUE)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																																.addComponent(
																																		jRadioButton2)
																																.addGroup(
																																		layout.createSequentialGroup()
																																				.addGap(21,
																																						21,
																																						21)
																																				.addGroup(
																																						layout.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																								.addComponent(
																																										jRadioButton8)
																																								.addComponent(
																																										jRadioButton6,
																																										javax.swing.GroupLayout.Alignment.LEADING)
																																								.addComponent(
																																										jRadioButton7,
																																										javax.swing.GroupLayout.Alignment.LEADING))))
																												.addGap(105,
																														105,
																														105)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addComponent(
																														jLabel3)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jRadioButton12)
																																				.addComponent(
																																						jRadioButton9))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGap(26,
																																		26,
																																		26)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jRadioButton13)
																																				.addComponent(
																																						jRadioButton10))
																																.addGap(18,
																																		18,
																																		18)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jRadioButton11)
																																				.addComponent(
																																						jRadioButton14)))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGap(10,
																																		10,
																																		10)
																																.addComponent(
																																		jTextField1,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		135,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addComponent(
																																		jLabel4)
																																.addGap(10,
																																		10,
																																		10)
																																.addComponent(
																																		jTextField2,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		151,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)))
																								.addGap(61,
																										61,
																										61)))
																.addGroup(
																		layout.createSequentialGroup()
																				.addComponent(
																						jLabel2)
																				.addContainerGap())))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jRadioButton1)
												.addComponent(jRadioButton2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jRadioButton3)
												.addComponent(jRadioButton6))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jRadioButton4)
												.addComponent(jRadioButton7))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jRadioButton5)
												.addComponent(jRadioButton8))
								.addGap(27, 27, 27)
								.addComponent(jLabel2)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jRadioButton9)
												.addComponent(jRadioButton10)
												.addComponent(jRadioButton11))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jRadioButton12)
												.addComponent(jRadioButton13)
												.addComponent(jRadioButton14))
								.addGap(38, 38, 38)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														20,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										34, Short.MAX_VALUE)
								.addComponent(jButton1).addGap(19, 19, 19)));

		pack();
	}// </editor-fold>

	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		jRadioButton3.setEnabled(false);
		jRadioButton4.setEnabled(false);
		jRadioButton5.setEnabled(false);
		jRadioButton6.setEnabled(true);
		jRadioButton7.setEnabled(true);
		jRadioButton8.setEnabled(true);

	}

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		jRadioButton6.setEnabled(false);
		jRadioButton7.setEnabled(false);
		jRadioButton8.setEnabled(false);
		jRadioButton3.setEnabled(true);
		jRadioButton4.setEnabled(true);
		jRadioButton5.setEnabled(true);

		// if( (jRadioButton3.isSelected()== false) &&
		// (jRadioButton4.isSelected() == false) && (jRadioButton5.isSelected()
		// == false) )
		// JOptionPane.showInternalMessageDialog(this,
		// "Select Winning Criteria", "Error", JOptionPane.ERROR_MESSAGE);
	}

	private String jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String teamName = jTextField1.getText();
		String teamName2 = jTextField2.getText();
		String wCriteria = "";
		String Continent = "";
		if (teamName.equals(""))
			JOptionPane.showMessageDialog(this, "Enter Team1 Name", "Error",
					JOptionPane.ERROR_MESSAGE);
		if (teamName2.equals(""))
			JOptionPane.showMessageDialog(this, "Enter Team2 Name", "Error",
					JOptionPane.ERROR_MESSAGE);
		if ((jRadioButton1.isSelected() == false)
				&& (jRadioButton2.isSelected() == false))
			JOptionPane.showMessageDialog(this, "Select Winning Criteria",
					"Error", JOptionPane.ERROR_MESSAGE);
		if ((jRadioButton9.isSelected() == false)
				&& (jRadioButton10.isSelected() == false)
				&& (jRadioButton11.isSelected() == false)
				&& (jRadioButton12.isSelected() == false)
				&& (jRadioButton13.isSelected() == false)
				&& (jRadioButton14.isSelected() == false))
			JOptionPane.showMessageDialog(this, "Select Continent", "Error",
					JOptionPane.ERROR_MESSAGE);
		else {
			if (jRadioButton3.isSelected()) {
				Criterion = "Time";
				wCriteria = jRadioButton3.getText();
			}
			// JOptionPane.showMessageDialog(null,teamName + wCriteria);}
			if (jRadioButton4.isSelected()) {
				Criterion = "Time";
				wCriteria = jRadioButton4.getText();
			}
			// JOptionPane.showMessageDialog(null,teamName + wCriteria);}
			if (jRadioButton5.isSelected()) {
				Criterion = "Time";
				wCriteria = jRadioButton5.getText();
			}
			// JOptionPane.showMessageDialog(null,teamName + wCriteria);}
			if (jRadioButton6.isSelected()) {
				Criterion = "Points";
				wCriteria = jRadioButton6.getText();
			}
			// JOptionPane.showMessageDialog(null,teamName + wCriteria);}
			if (jRadioButton7.isSelected()) {
				Criterion = "Points";
				wCriteria = jRadioButton7.getText();
			}
			// JOptionPane.showMessageDialog(null,teamName + wCriteria);}
			if (jRadioButton8.isSelected()) {
				Criterion = "Points";
				wCriteria = jRadioButton8.getText();
			}
			// JOptionPane.showMessageDialog(null,teamName + wCriteria);}

			if (jRadioButton9.isSelected()) {
				Continent = jRadioButton9.getText();
			}

			if (jRadioButton10.isSelected()) {
				Continent = jRadioButton10.getText();
			}
			if (jRadioButton11.isSelected()) {
				Continent = jRadioButton11.getText();
			}
			if (jRadioButton12.isSelected()) {
				Continent = jRadioButton12.getText();
			}
			if (jRadioButton13.isSelected()) {
				Continent = jRadioButton13.getText();
			}
			if (jRadioButton14.isSelected()) {
				Continent = jRadioButton14.getText();
			}

		}
		// _TeamStinson_1_sandra_172.24.205.97_3_TeamBarney_2_govind_172.24.213.113_5_gaurav_172.17.170.250_4

		if (!(teamName.equals("") || (teamName2.equals(""))
				|| (Criterion.equals("")) || (Continent.equals("")))) {
			String gameStr = "StartGame_" + Criterion + "_" + wCriteria + "_"
					+ Continent + "_" + (new Date().getTime()) + "_";
			JOptionPane.showMessageDialog(null, "Inputs Submitted. Press Start Game to Begin.");
			setVisible(false);
			myClientPrimaryData.gameStr = gameStr;

			myClientPrimaryData.myTeamName = teamName;
			myClientPrimaryData.oppTeamName = teamName2;

			System.out.println("Game string iframe is " + gameStr);
			return (gameStr);
		} else
			return null;
		// setVisible(false);
		// dispose();

	}

	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.ButtonGroup buttonGroup3;
	private javax.swing.ButtonGroup buttonGroup4;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton10;
	private javax.swing.JRadioButton jRadioButton11;
	private javax.swing.JRadioButton jRadioButton12;
	private javax.swing.JRadioButton jRadioButton13;
	private javax.swing.JRadioButton jRadioButton14;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JRadioButton jRadioButton5;
	private javax.swing.JRadioButton jRadioButton6;
	private javax.swing.JRadioButton jRadioButton7;
	private javax.swing.JRadioButton jRadioButton8;
	private javax.swing.JRadioButton jRadioButton9;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;

	// End of variables declaration

}
